name: Linting

on: [push]

jobs:
  linting:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest]
        os: [ubuntu-latest]
        node: [12]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
